version: '3.6'

networks: 
  default:
      name: DevResources

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
      - 4200:4200

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ./data/db:/data/db
    environment:
          - MONGO_DATA_DIR=/data/db
    ports:
      - 27017:27017